name: Deploy to Production

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to jer-serve via Jump Host
      uses: appleboy/ssh-action@v1.0.0
      with:
        # Target server (jer-serve via Tailscale)
        host: 100.74.87.20
        username: jeremy
        key: ${{ secrets.PRODUCTION_SSH_KEY }}
        port: 22
        
        # Jump host (Caddy server with public IP)
        proxy_host: 143.110.147.77
        proxy_username: root
        proxy_key: ${{ secrets.JUMP_HOST_SSH_KEY }}
        proxy_port: 22
        
        # Deployment script
        script: |
          cd /home/jeremy/apps/seating-charter
          
          # Pull latest changes
          git pull origin main
          
          # Setup Ruby environment
          export PATH="$HOME/.rbenv/bin:$PATH"
          eval "$(rbenv init -)"
          
          # Install/update dependencies
          bundle install --deployment --without development test
          
          # Run migrations
          RAILS_ENV=production bundle exec rails db:migrate
          
          # Precompile assets
          RAILS_ENV=production bundle exec rails assets:precompile
          
          # Restart the service
          sudo systemctl restart seating-charter
          
          # Wait for service to start
          sleep 5
          
          # Check service status
          sudo systemctl status seating-charter --no-pager
          
          echo "✅ Deployment completed successfully!"